spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_roa3Yf4zk
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: kakeibo-api          
  datasource:                  
    url: jdbc:postgresql://localhost:5432/kakeibo
    username: app
    password: password
  jpa:
    hibernate:
      ddl-auto: none           
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health        # Actuatorの公開エンドポイントをhealthのみに絞る